name: autofix.ci
on:
  push:
    branches: main
permissions:
  contents: read
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm install
      - run: pnpm run lint:fix
      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc